version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - unconvert
    - unparam

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes: github.com/Strob0t/CodeForge

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    colored-line-number: {}
  sort-results: true
