package mode

// BuiltinModes returns all built-in agent mode presets.
// Note: Mode-specific prompt content has been migrated to YAML files in
// internal/service/prompts/modes/. The commonRules content is in
// internal/service/prompts/behavior/. PromptPrefix is empty for all
// builtins; the PromptAssembler loads content from the YAML library.
func BuiltinModes() []Mode {
	modes := []Mode{
		{
			ID:               "architect",
			Name:             "Architect",
			Description:      "Designs system architecture, analyzes structure, and produces technical plans.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "PLAN.md",
			LLMScenario:      "think",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "coder",
			Name:             "Coder",
			Description:      "Implements features and writes production code.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf", "curl", "wget"},
			RequiredArtifact: "DIFF",
			LLMScenario:      "default",
			Autonomy:         3,
			PromptPrefix:     "",
		},
		{
			ID:               "reviewer",
			Name:             "Reviewer",
			Description:      "Reviews code for correctness, style, and potential issues.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			RequiredArtifact: "REVIEW.md",
			LLMScenario:      "review",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:            "debugger",
			Name:          "Debugger",
			Description:   "Diagnoses and fixes bugs by analyzing symptoms and tracing root causes.",
			Builtin:       true,
			Tools:         []string{"Read", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions: []string{"rm -rf", "curl", "wget"},
			LLMScenario:   "default",
			Autonomy:      3,
			PromptPrefix:  "",
		},
		{
			ID:               "tester",
			Name:             "Tester",
			Description:      "Writes and maintains tests, ensuring comprehensive coverage.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf", "curl", "wget"},
			RequiredArtifact: "TEST_REPORT",
			LLMScenario:      "default",
			Autonomy:         3,
			PromptPrefix:     "",
		},
		{
			ID:            "documenter",
			Name:          "Documenter",
			Description:   "Writes and maintains documentation, READMEs, and code comments.",
			Builtin:       true,
			Tools:         []string{"Read", "Write", "Edit", "Glob", "Grep"},
			DeniedTools:   []string{"Bash"},
			DeniedActions: []string{"rm", "curl", "wget"},
			LLMScenario:   "default",
			Autonomy:      3,
			PromptPrefix:  "",
		},
		{
			ID:               "refactorer",
			Name:             "Refactorer",
			Description:      "Improves code structure without changing external behavior.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf", "curl", "wget"},
			RequiredArtifact: "DIFF",
			LLMScenario:      "default",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "security",
			Name:             "Security Auditor",
			Description:      "Audits code for security vulnerabilities and compliance issues.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep", "Bash"},
			DeniedTools:      []string{"Write", "Edit"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "AUDIT_REPORT",
			LLMScenario:      "review",
			Autonomy:         2,
			PromptPrefix:     "",
		},
	}

	// Phase 21D: Moderator Agent Modes for multi-agent debate
	debateModes := []Mode{
		{
			ID:               "moderator",
			Name:             "Moderator",
			Description:      "Synthesizes proposals, identifies conflicts, and produces a unified decision. Used in multi-agent debate when the review router flags a step for moderated review.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "SYNTHESIS.md",
			LLMScenario:      "review",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "proponent",
			Name:             "Proponent",
			Description:      "Defends a proposed approach with evidence from the codebase. Used as the first step in multi-agent debate.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "PROPOSAL.md",
			LLMScenario:      "review",
			Autonomy:         2,
			PromptPrefix:     "",
		},
	}

	// Specialist modes adapted from agency-agents (MIT, msitarzewski/agency-agents)
	specialistModes := []Mode{
		{
			ID:               "devops",
			Name:             "DevOps Engineer",
			Description:      "Designs CI/CD pipelines, infrastructure-as-code, and deployment automation.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf", "curl | bash", "wget | bash"},
			RequiredArtifact: "DIFF",
			LLMScenario:      "default",
			Autonomy:         3,
			PromptPrefix:     "",
		},
		{
			ID:               "api-tester",
			Name:             "API Tester",
			Description:      "Tests APIs for functional correctness, security, and performance.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf", "curl | bash"},
			RequiredArtifact: "TEST_REPORT",
			LLMScenario:      "default",
			Autonomy:         3,
			PromptPrefix:     "",
		},
		{
			ID:               "benchmarker",
			Name:             "Performance Benchmarker",
			Description:      "Measures, analyzes, and optimizes system performance with statistical rigor.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf"},
			RequiredArtifact: "TEST_REPORT",
			LLMScenario:      "default",
			Autonomy:         3,
			PromptPrefix:     "",
		},
		{
			ID:               "frontend",
			Name:             "Frontend Developer",
			Description:      "Builds accessible, performant, responsive user interfaces.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf"},
			RequiredArtifact: "DIFF",
			LLMScenario:      "default",
			Autonomy:         3,
			PromptPrefix:     "",
		},
		{
			ID:               "backend-architect",
			Name:             "Backend Architect",
			Description:      "Designs backend systems: services, data models, APIs, and infrastructure patterns.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "PLAN.md",
			LLMScenario:      "think",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "lsp-engineer",
			Name:             "LSP Engineer",
			Description:      "Designs and plans multi-language LSP orchestration and semantic code graphs.",
			Builtin:          true,
			Tools:            []string{"Read", "Bash", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "PLAN.md",
			LLMScenario:      "think",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "orchestrator",
			Name:             "Orchestrator",
			Description:      "Coordinates multi-agent pipelines with quality gates, retries, and phase progression.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "PLAN.md",
			LLMScenario:      "think",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "evaluator",
			Name:             "Tool Evaluator",
			Description:      "Evaluates tools, libraries, and platforms with weighted scoring and TCO analysis.",
			Builtin:          true,
			Tools:            []string{"Read", "Bash", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit"},
			DeniedActions:    []string{"rm", "curl | bash", "wget | bash"},
			RequiredArtifact: "PLAN.md",
			LLMScenario:      "think",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "workflow-optimizer",
			Name:             "Workflow Optimizer",
			Description:      "Analyzes and optimizes development workflows, identifies bottlenecks, and designs automation.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			DeniedActions:    []string{"rm", "curl", "wget"},
			RequiredArtifact: "PLAN.md",
			LLMScenario:      "think",
			Autonomy:         2,
			PromptPrefix:     "",
		},
		{
			ID:               "infra-maintainer",
			Name:             "Infrastructure Maintainer",
			Description:      "Maintains system reliability, security, and performance of infrastructure.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf", "curl | bash", "wget | bash"},
			RequiredArtifact: "DIFF",
			LLMScenario:      "default",
			Autonomy:         3,
			PromptPrefix:     "",
		},
		{
			ID:               "prototyper",
			Name:             "Rapid Prototyper",
			Description:      "Builds functional prototypes fast with strict scope discipline and hypothesis-driven development.",
			Builtin:          true,
			Tools:            []string{"Read", "Write", "Edit", "Bash", "Glob", "Grep"},
			DeniedActions:    []string{"rm -rf"},
			RequiredArtifact: "DIFF",
			LLMScenario:      "default",
			Autonomy:         4,
			PromptPrefix:     "",
		},
	}

	modes = append(modes, debateModes...)
	modes = append(modes, specialistModes...)

	// Goal-researcher mode for agent-driven goal discovery (GSD style).
	modes = append(modes,
		// Goal-researcher mode for agent-driven goal discovery (GSD style).
		Mode{
			ID:           "goal-researcher",
			Name:         "Goal Researcher",
			Description:  "Analyzes a repository and interviews the user to discover project goals (GSD).",
			Builtin:      true,
			Tools:        []string{"Read", "Glob", "Grep", "ListDir", "propose_goal", "Write"},
			DeniedTools:  []string{"Edit", "Bash"},
			LLMScenario:  "think",
			Autonomy:     2,
			PromptPrefix: "",
		},
		// Review-refactor pipeline modes (Phase 31).
		Mode{
			ID:               "boundary-analyzer",
			Name:             "Boundary Analyzer",
			Description:      "Analyzes project structure to identify boundary files between modules, services, and language layers.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep", "ListDir"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			RequiredArtifact: "BOUNDARIES.json",
			LLMScenario:      "plan",
			Autonomy:         4,
			PromptPrefix:     "",
		},
		Mode{
			ID:               "contract-reviewer",
			Name:             "Contract Reviewer",
			Description:      "Reviews cross-layer contracts for consistency between boundary files.",
			Builtin:          true,
			Tools:            []string{"Read", "Glob", "Grep"},
			DeniedTools:      []string{"Write", "Edit", "Bash"},
			RequiredArtifact: "CONTRACT_REVIEW.md",
			LLMScenario:      "review",
			Autonomy:         2,
			PromptPrefix:     "",
		},
	)

	return modes
}
