#!/usr/bin/env bash
# scripts/generate-secrets.sh -- Generate the secret files for docker-compose.prod.yml
#
# Usage: ./scripts/generate-secrets.sh [secrets_dir]
# Default dir: $SECRETS_DIR, else ./secrets (the default of docker-compose.prod.yml)
#
# Random secrets are created once and never overwritten; delete a file and
# re-run to rotate it. Values are hex, so they are safe inside connection URLs.
# The derived files (database-url, nats-url, nats-auth.conf) are rebuilt from
# the random secrets on every run, so they cannot drift apart.
#
# Environment: POSTGRES_USER and POSTGRES_DB (default: codeforge) must match
# the values docker-compose.prod.yml runs with.
set -euo pipefail

SECRETS_DIR="${1:-${SECRETS_DIR:-./secrets}}"
PG_USER="${POSTGRES_USER:-codeforge}"
PG_DB="${POSTGRES_DB:-codeforge}"

# URL userinfo and path characters that need no escaping.
URL_SAFE='^[A-Za-z0-9._~-]+$'

# Compose bind-mounts file secrets with their host owner and mode (uid/gid/mode
# only work in Swarm), and core, worker and nats do not run as the host user.
# The files are therefore world-readable (0644) inside a private (0700)
# directory, which keeps other host users out.
umask 077
mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

write_file() {
    local file="$SECRETS_DIR/$1"
    printf '%s' "$2" > "$file"
    chmod 644 "$file"
}

# generate <name> <value>: write a random secret unless the file exists.
generate() {
    local name="$1"
    if [ -f "$SECRETS_DIR/$name" ]; then
        chmod 644 "$SECRETS_DIR/$name"
        echo "Secret $name already exists, skipping"
        return
    fi
    write_file "$name" "$2"
    echo "Generated $name"
}

# read_url_safe <name>: print a secret that is embedded in a URL or config.
read_url_safe() {
    local value
    value="$(< "$SECRETS_DIR/$1")"
    if [[ ! "$value" =~ $URL_SAFE ]]; then
        echo "ERROR: $SECRETS_DIR/$1 contains characters that are not URL-safe" \
            "(older versions of this script wrote base64); delete it and re-run" >&2
        exit 1
    fi
    printf '%s' "$value"
}

if [[ ! "$PG_USER" =~ $URL_SAFE ]] || [[ ! "$PG_DB" =~ $URL_SAFE ]]; then
    echo "ERROR: POSTGRES_USER and POSTGRES_DB must match $URL_SAFE" >&2
    exit 1
fi

generate postgres-password "$(openssl rand -hex 32)"
generate nats-user "codeforge-$(openssl rand -hex 4)"
generate nats-pass "$(openssl rand -hex 32)"
generate litellm-master-key "sk-$(openssl rand -hex 32)"
generate codeforge-auth-jwt-secret "$(openssl rand -hex 32)"
generate codeforge-internal-key "$(openssl rand -hex 32)"

# Self-signed server certificate for PostgreSQL TLS. The clients use
# sslmode=require (encrypted, not verified); replace both files with a
# CA-signed pair and switch the DSNs to sslmode=verify-full to verify it.
if [ -f "$SECRETS_DIR/postgres-tls.crt" ] && [ -f "$SECRETS_DIR/postgres-tls.key" ]; then
    chmod 644 "$SECRETS_DIR/postgres-tls.crt" "$SECRETS_DIR/postgres-tls.key"
    echo "Secret postgres-tls.crt/.key already exist, skipping"
else
    openssl req -x509 -newkey rsa:3072 -nodes -days 3650 -subj "/CN=postgres" \
        -addext "subjectAltName=DNS:postgres" \
        -keyout "$SECRETS_DIR/postgres-tls.key" -out "$SECRETS_DIR/postgres-tls.crt" 2> /dev/null
    chmod 644 "$SECRETS_DIR/postgres-tls.crt" "$SECRETS_DIR/postgres-tls.key"
    echo "Generated postgres-tls.crt/.key (self-signed, CN=postgres)"
fi

PG_PASS="$(read_url_safe postgres-password)"
NATS_USER="$(read_url_safe nats-user)"
NATS_PASS="$(read_url_safe nats-pass)"

write_file database-url "postgresql://${PG_USER}:${PG_PASS}@postgres:5432/${PG_DB}?sslmode=require"
write_file nats-url "nats://${NATS_USER}:${NATS_PASS}@nats:4222"
write_file nats-auth.conf "# Generated by scripts/generate-secrets.sh from nats-user and nats-pass
authorization {
  user: \"${NATS_USER}\"
  password: \"${NATS_PASS}\"
}
"
echo "Wrote database-url, nats-url, nats-auth.conf"

echo ""
echo "Secrets generated in $SECRETS_DIR"
echo "Add $SECRETS_DIR to .gitignore (if not already) to prevent committing secrets."
