-- +goose Up
ALTER TABLE runs ADD COLUMN tokens_in  BIGINT NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN tokens_out BIGINT NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN model      TEXT   NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE runs DROP COLUMN IF EXISTS model;
ALTER TABLE runs DROP COLUMN IF EXISTS tokens_out;
ALTER TABLE runs DROP COLUMN IF EXISTS tokens_in;
