-- +goose Up
-- KI-147: one turn's messages are inserted in a single batch and share one
-- created_at (the transaction start), so ordering by created_at put tool
-- results before their calls. seq records the insert order. Existing rows are
-- numbered by created_at and, for equal timestamps, by heap position, which
-- for rows written in one batch is the best record of their insert order left
-- (id is random).
ALTER TABLE conversation_messages ADD COLUMN seq BIGINT;

UPDATE conversation_messages m
SET seq = o.rn
FROM (
    SELECT id, row_number() OVER (ORDER BY created_at, ctid) AS rn
    FROM conversation_messages
) o
WHERE m.id = o.id;

ALTER TABLE conversation_messages ALTER COLUMN seq SET NOT NULL;
ALTER TABLE conversation_messages ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('conversation_messages', 'seq'), COALESCE(MAX(seq), 0) + 1, false)
FROM conversation_messages;

-- Serves the per-conversation listing in seq order and every lookup by
-- conversation_id the old index served.
CREATE INDEX idx_conversation_messages_conv_seq ON conversation_messages (conversation_id, seq);
DROP INDEX IF EXISTS idx_conversation_messages_conv;

-- +goose Down
CREATE INDEX IF NOT EXISTS idx_conversation_messages_conv ON conversation_messages (conversation_id);
DROP INDEX IF EXISTS idx_conversation_messages_conv_seq;
ALTER TABLE conversation_messages DROP COLUMN IF EXISTS seq;
